# save this a simple-job.yaml
apiVersion: batch/v1
kind: Job

metadata:
  name: batch-job-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: my-job
          image: alpine
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo Fourth Batch Job; sleep 2']
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
  ttlSecondsAfterFinished: 60
