# save this a simple-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-example
spec:
  template:
    spec:
      containers:
        - name: my-job
          image: alpine
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo Second Batch Job; sleep 10']
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
